#!/usr/bin/env python3.10
from coordinates import get_coordinates
from weather_api_service import get_weather
from weather_formatter import format_weather
from exceptions import CantGetCoordinates, ApiServiceError
from history import JsonStorage, save

def main() -> None:
    try:
        coordinates = get_coordinates()
    except CantGetCoordinates:
        print("Unable to get GPS data from Mac")
        exit(1)
    try:
        weather = get_weather(coordinates)
    except ApiServiceError:
        print("Unable to get OpenWeather data")
        exit(1)
    save(JsonStorage(weather)) 
    print(format_weather(weather))

if __name__ == "__main__":
    main()

